# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALu5eySLJSxRmgrSnzAb8-lm8OJQwFdk
"""

import requests
import pandas as pd
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup

link = 'Link-kalian'
request = requests.get(link)
UserAgent = Request(link, headers = {'User-Agent': 'Mozilla/5.0'})
html_text = urlopen(UserAgent)

soup = BeautifulSoup(html_text, "html.parser")

daftar = soup.find_all("tag html",{"class":"class yang di tuju"})

judul = [tag.find_previous('tag',{'class':'nama class'}).text.strip() if tag.find_previous('tag',{'class':'nama class'}) is not None else None for tag in daftar]
tanggal = [tag.find_previous('tag',{'class':'nama class'}).text.strip() if tag.find_previous('tag',{'class':'nama class'}) is not None else None for tag in daftar]

df = pd.DataFrame({
        'Judul': judul,
        'Tanggal': tanggal
})

print(df)

df.to_excel('nama file.xlsx', index=False)